### PR TITLE
Backports into stable-4.1

### PR DESCRIPTION
**Pull request by fghaas**
* Improve logging in `hastexo.provider`
* Exclude abstract methods from coverage
* Fix defaults for `Stack.key` and `Stack.password`

### CODE REVIEW

**Comment by fghaas** [comment]
@mrtmm No particular urgency on this one; review at your convenience. :)

**Comment by fghaas** [comment]
@mrtmm I think this is now good to merge so we can release 4.1.13 — unless you have objections.

**Comment by fghaas** [comment]
No idea why the build is failing, looks like a problem on GitHub's workflow actions infrastructure. [setuptools-scm](https://pypi.org/project/setuptools-scm/) is certainly alive and kicking.

**Comment by fghaas** [comment]
Build issues are now resolved.

**Review by mrtmm — APPROVED** [review]
Looks good to me.

**Comment by fghaas** [comment]
Ack, thanks! I've cut a 4.1.13 release.

**Pull request merged**
