### PR TITLE
Bump version: 3.4.2 → 3.5.0

### PR DESCRIPTION
**Pull request by arbrandes**

### CODE REVIEW

**Comment by fghaas** [comment]
I thought we'd make this one 3.4.3, and #111 3.5.0. Or do you think we ought to bump the major for #111?

**Comment by arbrandes** [comment]
> I thought we'd make this one 3.4.3, and #111 3.5.0. Or do you think we ought to bump the major for #111?

Either way is fine.  But I figured the retry was sufficiently different, and an enhancement at that, to warrant a minor bump (vs a patch bump).

**Comment by fghaas** [comment]
I'll defer to your call. I guess it's debatable whether being persistent with database updates is a bug fix, or an enhancement. But yeah I put it into the changelog as an enhancement myself, so you're right. :)

**Comment by arbrandes** [comment]
Merged.  I'll need you to upload to pypi, though, as I'm no longer an admin. :)

**Comment by fghaas** [comment]
[Done](https://pypi.org/project/hastexo-xblock/#history), thank you!

**Pull request merged**
