### PR TITLE
Disable page auto-scroll when terminal gets focused

### PR DESCRIPTION
**Pull request by mrtmm**

### CODE REVIEW

**Review by fghaas — CHANGES_REQUESTED** [review]
The functional change itself is perfectly fine. Can we please have a little more detail in the commit message, though? Such as, what "auto-scroll" means, why we consider it detrimental, that it affects Chromium and Safari users but not Firefox users, and also that the patch fixes the behavior on Chrome (and probably all Chromium-based browsers), but not on Safari?

**Comment by mrtmm** [comment]
Sure, added a more informative commit message.

**Comment by fghaas** [comment]
> Safari however, is auto-scrolling and this commit does not enable that.

This part of the commit message is still confusing. `s/enable/disable/` ?

**Comment by mrtmm** [comment]
Yes, sorry that should be `disable`.

**Pull request merged**
