### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by arbrandes**

### CODE REVIEW

**Comment by fghaas** [comment]
Very cool. Looks great to me. Thanks!

**Comment by arbrandes** [comment]
@fghaas, thanks!  This is up for testing at the workshop stack.

[This HX201 run](https://workshop.hastexo.com/courses/course-v1:hastexo+hx201+dev-juju/about) should launch in Sto2, and [this one](https://workshop.hastexo.com/courses/course-v1:hastexo+hx201+dev-juju-kna1/about) should launch in Kna1.

If this works as usual, I'll merge it in.

**Comment by arbrandes** [comment]
Getting Swift auth errors right after CREATE_COMPLETE.  Will investigate tomorrow.

```
[service_variant=lms][swiftclien ERROR [app0  1916] [client.py:1669] - Authorization Failure. Authorization failed: Cannot authenticate without an auth_url
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/swiftclient/client.py", line 1635, in _retry
    self.url, self.token = self.get_auth()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/swiftclient/client.py", line 1587, in get_auth
    timeout=self.timeout)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/swiftclient/client.py", line 662, in get_auth
    auth_version=auth_version)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/swiftclient/client.py", line 582, in get_auth_keystone
    raise ClientException('Authorization Failure. %s' % err)
ClientException: Authorization Failure. Authorization failed: Cannot authenticate without an auth_url
```

**Comment by arbrandes** [comment]
Problem fixed.  Tested on workshop stack with 3 app servers and two courses on different regions, including stack resets and progress checks.

**Pull request merged**
