### PR TITLE
v0.5.0

### PR DESCRIPTION
**Pull request by arbrandes**

### CODE REVIEW

**Comment by fghaas** [comment]
Slick! Has this been tested against both a Keystone v3 and a v2 environment?

**Comment by arbrandes** [comment]
I tested it against City and Elastx, so, presumably, yes.

**Comment by fghaas** [comment]
Great. Will you publish to PyPI, as usual?

**Comment by arbrandes** [comment]
Done: https://pypi.python.org/pypi/hastexo-xblock/0.5.0

**Comment by fghaas** [comment]
Thanks!

**Pull request merged**
